ARG VERSION=v3.2.1


FROM alpine:3.20 AS envtools
RUN apk add --no-cache gettext


FROM prom/prometheus:${VERSION}
COPY --from=envtools /usr/bin/envsubst /usr/local/bin/envsubst
COPY prom.yml.tpl /etc/prometheus/prom.yml.tpl
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]


CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]
